spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/offers
      auto-index-creation: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-bean-definition-overriding: true
offer:
  http:
    scheduler:
      delay: PT3H
      enabled: true
    client:
      config:
        uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
        port: 5057
        connectionTimeout: 1000
        readTimeout: 1000

http:
  offers:
    scheduler:
      request:
        delay: PT1s


auth:
  jwt:
    secret: ${JWT_SECRET}
    issuer: job-offers-backend
    expiration-days: 30